Policeのページを削除 & 細かい修正
Neko7sora/kpw-web pull request #21
Opened 2022-10-31 15:05 UTC by Jumala9163

・サーバールールを最新のものに変更
・Discordのページに何も書かれていなかったので適当に内容を追加

2022-10-31 15:07 UTC, tier940 approved these changes
LGTM

2022-10-31 15:25 UTC, Neko7sora requested changes

2022-10-31 15:25 UTC, Neko7sora commented on path/docs/mkdocs/docs/about/rule.md
> +3. discord鯖宣伝﻿ 以外で 宣伝、営業、勧誘に当たる行為はしないでください
![image](https://user-images.githubusercontent.com/75793267/199044308-0586e7af-5321-468a-a20d-524d8d534bc0.png)
```suggestion
3. discord鯖宣伝 以外で 宣伝、営業、勧誘に当たる行為はしないでください
```
Hex: `EF BB BF` を削除してください。

2022-11-01 15:28 UTC, Neko7sora approved these changes

2022-11-01 15:29 UTC, merged